### ISSUE TITLE
udppm is not working.

### ISSUE THREAD

**Issue by phantomcraft** [z3APA3A/3proxy#499]
When I changed to the latest commit, my udppm stopped working:

When invoked, it shows an endless looping:

```
user@localhost:~$ udppm -l -i127.0.0.1 1053 1.1.1.1 53
200807013333.333 1053 00000 - 127.0.0.1:1053 0.0.0.0:0 0 0 0 Accepting connections [65277/834156352]
200807013350.641 1053 00100 - 127.0.0.1:1053 0.0.0.0:0 0 0 0 
200807013350.642 1053 00100 - 0.0.0.0:0 0.0.0.0:0 0 0 0 
200807013350.643 1053 00100 - 0.0.0.0:0 0.0.0.0:0 0 0 0 
[...]
200807013350.644 1053 00100 - 0.0.0.0:0 0.0.0.0:0 0 0 0 
200807013350.646 1053 00100 - 0.0.0.0:0 0.0.0.0:0 0 0 0 
[...]
```

Here I invoked with dig app:

```
user@localhost:~$ dig @127.0.0.1 -p 1053 goo.gl

; <<>> DiG 9.16.4-Debian <<>> @127.0.0.1 -p 1053 goo.gl
; (1 server found)
;; global options: +cmd
;; connection timed out; no servers could be reached
```

The same error occurs when an IPv6 address is used as parent address.

**Comment by z3APA3A** [comment]
Should be fixed with 1fd759d3274c5d098eaf29e69b85e9a39c5ab477

**Comment by phantomcraft** [comment]
When the upstream UDP address is IPv6, the same problem persists:


```
user@localhost:~$ udppm -l -i127.0.0.1 1053 [::1] 53
200808221945.614 1053 00000 - 127.0.0.1:1053 0.0.0.0:0 0 0 0 Accepting connections [267381/4284663616]
200808221949.910 1053 00100 - 127.0.0.1:1053 0.0.0.0:0 0 0 0 
200808221949.912 1053 00100 - 0.0.0.0:0 0.0.0.0:0 0 0 0 
200808221949.913 1053 00100 - 0.0.0.0:0 0.0.0.0:0 0 0 0 
[...]
200808221949.932 1053 00100 - 0.0.0.0:0 0.0.0.0:0 0 0 0 
200808221949.934 1053 00100 - 0.0.0.0:0 0.0.0.0:0 0 0 0 
200808221949.935 1053 00100 - 0.0.0.0:0 0.0.0.0:0 0 0 0 
200808221949.937 1053 00100 - 0.0.0.0:0 0.0.0.0:0 0 0 0 
[...]
```
```

user@localhost:~$ dig @127.0.0.1 -p 1053 ixquick.com

; <<>> DiG 9.16.4-Debian <<>> @127.0.0.1 -p 1053 ixquick.com
; (1 server found)
;; global options: +cmd
;; connection timed out; no servers could be reached

```

**Comment by phantomcraft** [comment]
udppm of 3proxy-0.8.13 also doesn't work when the upstream address is IPv6:

```
user@localhost:~$ /dev/shm/3proxy-0.8.13/src/udppm -l -i127.0.0.1 1053 [::1] 53
200808222627.518 1053 00000 - 127.0.0.1:1053 0.0.0.0:0 0 0 0 Accepting connections [284132/2405439296]
200808222631.718 1053 00097 - 127.0.0.1:51577 ::1:53 0 0 0 
200808222636.717 1053 00097 - 127.0.0.1:51577 ::1:53 0 0 0 
200808222641.717 1053 00097 - 127.0.0.1:51577 ::1:53 0 0 0 
```

```
user@localhost:~$ dig @127.0.0.1 -p 1053 ixquick.com

; <<>> DiG 9.16.4-Debian <<>> @127.0.0.1 -p 1053 ixquick.com
; (1 server found)
;; global options: +cmd
;; connection timed out; no servers could be reached
```

**Comment by z3APA3A** [comment]
standalone services assume -4 by default, add either of -6, -46, -64

**Comment by phantomcraft** [comment]
@z3APA3A 

Ok, but 3proxy-0.8.13 (stable) doesn't work in udppm even if using -6, -46 or -64
