### ISSUE TITLE
tcppm and udppm can't be killed by CTRL+C

### ISSUE THREAD

**Issue by phantomcraft** [z3APA3A/3proxy#529]
I'm using the latest development version.

When I invoke tcppm or udppm in command line, I can't finish the process with CTRL+C, I have to use killall:

`killall -9 tcppm`
`killall -9 udppm`

When used in this way, it's ok

```
user@localhost:~$ 3proxy << EOT
log
auth iponly
allow *
tcppm -46 -i127.0.0.1 1081 [::ffff:127.0.0.1] 1080
EOT
```

**Comment by z3APA3A** [comment]
probably. it can happen with udppm and I will correct it, but it shouldn't happen with tcppm. Are you sure you can really see this behavior with tcppm?

**Comment by z3APA3A** [comment]
udppm should be fixed with ef6d1d14e62f1dc92af0dbf675541444012135c0.

**Comment by phantomcraft** [comment]
@z3APA3A 

Yes, tcppm is bugged too.

**Comment by z3APA3A** [comment]
Can't reproduce it under Ubuntu:
https://s.mail.ru/3hdJ/362gonkv6

**Comment by z3APA3A** [comment]
Try with latest commit https://github.com/z3APA3A/3proxy/commit/c63392f1eafc0d64a899818795425f486f9cb2fc, it should fix the issue.

**Comment by phantomcraft** [comment]
Thanks @z3APA3A , now it's fixed on both tcppm and udppm.

**Comment by phantomcraft** [comment]
The same error persists in 3proxy-0.9.0-rc.

**Comment by z3APA3A** [comment]
yes, 0.9-rc was released before the patch. The patches is in the master and will be in 0.9 release.

**Comment by phantomcraft** [comment]
This problem returned in tcppm and udppm in 0.9.1 and development version, can't be killed by CTRL+C, only "killall -9".

I'm using Debian testing (I instaled the .deb package of 0.9.1).

**Comment by z3APA3A** [comment]
Yes, the patch was lost on merge :( fixed in master and devel.

**Comment by phantomcraft** [comment]
The problem is back with 0.9.3 and development version in tcppm and udppm.

**Comment by z3APA3A** [comment]
I've checked, the proposed fix is here in master, devel and released 0.9.3 tag (3proxy doesn't set sigmask if tcppm/udppm/etc are executed as standalone applications).  Can you provide more details?

**Comment by phantomcraft** [comment]
/\ I use Debian testing amd64, my GCC version is 9.2.1, using bash as shell and RoxTerm as terminal.

I just compiled 3proxy here and tested tcppm and udppm, they don't respond when I press CTRL+C, I have to kill by using **_killall -9 tcppm/udppm_**.
