### ISSUE TITLE
Four crashing points in 0.9.0

### ISSUE THREAD

**Issue by Shawn-Tong** [z3APA3A/3proxy#546]
I've tested it for a few days and found four crashing points in the recent version 0.9.0.

```
1. kernel: traps: 3proxy[22975] trap divide error ip:407845 sp:7ff951c00110 error:0 in 3proxy[400000+2a000] (very often)
2. kernel: 3proxy[18390]: segfault at 5f991592 ip 00000000004042c3 sp 00007f9f51c81400 error 4 in 3proxy[400000+29000] (often)
3. kernel: 3proxy[5090]: segfault at 5f9f93c2 ip 0000000000404293 sp 00007f4992c67400 error 4 in 3proxy[400000+29000] (often)
4. kernel: 3proxy[29122]: segfault at 5f81e22c ip 0000000000404213 sp 00007f89a2ecb400 error 4 in 3proxy[400000+29000] (sometimes)
```

Here are the results of the `addr2line` command.

```
1. 3proxy/src/auth.c:577 (discriminator 2)
param->bandlims[i]->nexttime = msec + nsleeptime + ((param->bandlims[i]->rate > 1000000)? ((nbytesin/32)*(256000000/param->bandlims[i]->rate)) : (nbytesin * (8000000/param->bandlims[i]->rate)));

2. 3proxy/src/proxymain.c:1166
if(hst->name)myfree(hst->name);

3. 3proxy/src/proxymain.c:1163
if(ul->user)myfree(ul->user);

4. 3proxy/src/proxymain.c:1158 (discriminator 2)
for(ipl = ac->src; ipl; ipl = (struct iplist *)itfree(ipl, ipl->next));
```

I hope you can fix them to make 3proxy perfect. Thank you.

**Comment by z3APA3A** [comment]
All issues seems to be result of 3proxy config reload under insufficient memory condition. While 3proxy may (somehow) work under low memory (of cause, some operations will fail), there is no chance for 3proxy to survive configuration reload in this case. I have added additional checks for memory allocation, so 3proxy should not crash now, but it will exit on configuration reading in the case of memory allocation failure. Please try to test the version from current master.

**Comment by Shawn-Tong** [comment]
I can't start the service now. Error message:

```
Service not started on line: 8: insufficient memory
Command: 'proxy' failed with code 40, line 8
Command: 'include' failed with code 8, line 8
```

3proxy.cfg
```
nscache 65536
nserver 8.8.8.8
nserver 8.8.4.4

config /conf/3proxy.cfg
log /logs/3proxy%y%m%d.log D

proxy
```

**Comment by phantomcraft** [comment]
The last commit for now tried to fix the problem on development version, but the same error still persists when using dnspr in 3proxy binary.

**Comment by z3APA3A** [comment]
@Shawn-Tong forgot to commit latest changes, should be fixed now.

**Comment by Shawn-Tong** [comment]
compile error:

```
proxymain.c: In function ‘copyacl’:
proxymain.c:1187:1: error: duplicate label ‘ERRORCHAINS’
 ERRORCHAINS:
 ^
proxymain.c:1185:1: note: previous definition of ‘ERRORCHAINS’ was here
 ERRORCHAINS:
 ^
```

**Comment by z3APA3A** [comment]
should be fixed with 3a31da9b3db23c0f90c48e337ae94234ba128b6b

**Comment by Shawn-Tong** [comment]
The 'divided by zero' crashing point isn't fixed yet.

`kernel: traps: 3proxy[16793] trap divide error ip:4079f5 sp:7f3898a78110 error:0 in 3proxy[400000+2a000]`

```
addr2line -e 3proxy 4079f5
3proxy/src/auth.c:578 (discriminator 2)
param->bandlims[i]->nexttime = msec + nsleeptime + ((param->bandlims[i]->rate > 1000000)? ((nbytesin/32)*(256000000/param->bandlims[i]->rate)) : (nbytesin * (8000000/param->bandlims[i]->rate)));
```

**Comment by z3APA3A** [comment]
@Shawn-Tong 
try the latest master

**Comment by Shawn-Tong** [comment]
Thanks for the fix. I'll run it for a few days to confirm everything is fixed.

**Comment by Shawn-Tong** [comment]
The CPU usage boosts to 120% when using the new version 0.9.1 under high load.

When I switch to version 0.9.0-devel, the CPU drops to 30% immediately, under the same load.

**Comment by z3APA3A** [comment]
Does CPU boosts on configuration reloads or there is a permanent increase?

**Comment by Shawn-Tong** [comment]
It is a permanent increase lasting all the time.

**Comment by z3APA3A** [comment]
how often do you reload configuration?

**Comment by Shawn-Tong** [comment]
It's strange that there is no problem now when I switch from 0.9-devel to 0.9.1 again. The CPU usage didn't change. I will continue to monitor this issue.

A suggestion, please change the version info for this command `3proxy -v` so that I can know which version I'm running now.

**Comment by z3APA3A** [comment]
Version prior to https://github.com/z3APA3A/3proxy/commit/32d5dc05c350f3f72490183fe4d9ce81393a9ef9 could be CPU-intensive on large band limiter lists.

**Comment by Shawn-Tong** [comment]
I have 20 bandwidth limit rules. The difference is about 1~2% on the CPU usage between two versions.

**Comment by z3APA3A** [comment]
Current master adds 1 additional sync check on every read/write if banlimiters are used to avoid race conditions comparing with latest release, it can add 1-2% overhead on large loads where blocking is actually required. I will try to optimize it in non-blocking way on the next approach to bandlimiters.

**Comment by Shawn-Tong** [comment]
Yes, the `si` (software interrupt) is very high because of the blocking.

3proxy 0.9.1-latest
```
%Cpu(s):  4.1 us,  8.0 sy,  0.0 ni, 46.6 id,  0.0 wa,  0.0 hi, 41.2 si,  0.0 st

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
13796 proxy     20   0  904540 262372    936 S  90.0  6.8 506:08.81 3proxy 
```

3proxy 0.9.0-devel
```
%Cpu(s):  4.8 us,  8.7 sy,  0.0 ni, 45.9 id,  0.2 wa,  0.0 hi, 40.4 si,  0.0 st

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
12618 proxy     20   0  838024 166420    852 S  88.5  4.3   2:06.59 3proxy
```

But there is no change after removing all the bandwidth limit rules. It seems not caused by the limiters.

squid 2.7 under a similar load
```
%Cpu(s):  0.7 us,  1.7 sy,  0.0 ni, 94.8 id,  0.0 wa,  0.0 hi,  1.4 si,  1.4 st

  PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND
23910 squid     20   0  192168 173088   1732 R  4.3 17.1   2818:51 squid
```

**Comment by z3APA3A** [comment]
This load is unrelated to bandlimiter blocking, additional lock in banlimiters can not add more than 1-2% to CPU usage. A main reason of high si in 3proxy is one connection - one thread model and splice usage for 0-copy, see https://3proxy.ru/highload.asp. You can decrease si by disabling splice, but it will increase overall CPU usage. One connection - one thread model makes 3proxy simple, but this model is not intended for high loads. I'm currently working to implement workers model with fibers in 3proxy 10, it will make it more suitable for high loads.

**Comment by Shawn-Tong** [comment]
Great, I'm looking forward to 3proxy 10.
